### ISSUE TITLE
download links broken

### ISSUE THREAD

**Issue by robsonsobral** [meerkatzenwildschein/jeboorker#1]
Hi!

I just want to let you know that the download links are broken.

**Comment by meerkatzenwildschein** [comment]
Hi, thanks for the hint, I hope they're working now.

**Comment by SicariusNoctis** [comment]
Hmm... they appear to be dead again

**Comment by meerkatzenwildschein** [comment]
Which download link you tried? The one mentioned at the start page which points to the [release section](https://github.com/meerkatzenwildschein/jeboorker/releases) seems to do it's job.
