### ISSUE TITLE
OSX version

### ISSUE THREAD

**Issue by jeffmcneill** [meerkatzenwildschein/jeboorker#2]

**Comment by meerkatzenwildschein** [comment]
I'm sorry but I have no OSX version planed. I did not have any apple device for testing and I think there will be some issues with the desktop integration.

**Comment by jeffmcneill** [comment]
What is the app written in? Usually there is some wrapper to get linux apps to run, without native integration (e.g., GIMP, Inkscape). Let me know and I can try and figure it out.

**Comment by meerkatzenwildschein** [comment]
Jeboorker is written in Java. I think the [Linux](http://morologia.net/jeboorker/download.php?f=jeboorker.tar.gz) download is a trial worth but I'm sure there will be Bugs on a never tested system. You need java version 7 or greater. There are also the dependencies `xdg-utils,unrar,rar,desktop-file-utils` for the linux platform (The dependency binaries must be located in the default system path). They're necessary to handle rar archives, find the right application to open an ebook or just opening a file or directory chooser.

Last but not least there is a library `libjmupdf64.so` in the lib path of Jeboorker. I'm not sure what to do with this. It is needed to render pdf pages and ebook covers. This library comes from the [jmupdf project](https://code.google.com/p/jmupdf/). I think it could be necessary to compile it under OSX and replace the linux library.

To run Jeboorker from scratch, open a command line, extract the Jeboorker tar.gz archive and change to the extracted folder. Now you can try to start the application with: `java -splash:splashscreen.gif -client -Xmx512m -XX:+UseParNewGC -XX:MaxHeapFreeRatio=20 -XX:MinHeapFreeRatio=10 -XX:+AggressiveOpts -cp lib/ant-1.7.0.jar:lib/ant-launcher-1.7.0.jar:lib/bcpkix-jdk15on-1.47.jar:lib/bcprov-ext-jdk15on-1.47.jar:lib/bcprov-jdk15on-1.47.jar:lib/bcprov-jdk16-1.46.jar:lib/bounce-0.19_1.jar:lib/commons-1.0.jar:lib/commons-codec-1.6.jar:lib/commons-compress-1.4.1.jar:lib/commons-exec-1.3.jar:lib/commons-io-2.4.jar:lib/commons-lang-2.6.jar:lib/commons-logging-1.0.4.jar:lib/commons-logging-1.1.3.jar:lib/commons-net-2.2.jar:lib/commons-swing-1.0.jar:lib/commons-vfs-1.0.jar:lib/commons.swing-1.0.jar:lib/dropbox-core-sdk-1.7.7.jar:lib/epublib-3.1.jar:lib/gson-2.3.1.jar:lib/h2-1.4.188.jar:lib/htmlcleaner-2.2.jar:lib/httpclient-4.3.3.jar:lib/httpcore-4.3.2.jar:lib/httpmime-4.3.3.jar:lib/itext-5.jar:lib/jackson-core-2.4.0-rc3.jar:lib/javax.websocket-api-1.1.jar:lib/jcl-over-slf4j-1.7.7.jar:lib/jdom-1.1.jar:lib/jeboorker-main-0.4.9.jar:lib/jempbox-0.2.0_1.jar:lib/jgoodies-common-1.7.0.jar:lib/jgoodies-looks-2.5.3.jar:lib/jmupdf-0.5.0.jar:lib/jmupdf-viewer-0.5.0.jar:lib/jna-3.4.0.jar:lib/jpushbullet2-0.3.0-SNAPSHOT.jar:lib/jsoup-1.8.1.jar:lib/junique-1.0.4.jar:lib/junit-3.8.1.jar:lib/jxlayer-3.0.4.jar:lib/kxml2-2.3.0.jar:lib/l2fprod-7.3_1.jar:lib/miglayout-3.7.4.jar:lib/miglayout-core-5.0.jar:lib/miglayout-swing-5.0.jar:lib/myswing-1.0.jar:lib/ormlite-core-4.48.jar:lib/ormlite-jdbc-4.48.jar:lib/platform-3.4.0.jar:lib/slf4j-api-1.7.7.jar:lib/truezip-driver-file-7.7.2.jar:lib/truezip-driver-zip-7.7.2.jar:lib/truezip-file-7.7.2.jar:lib/truezip-kernel-7.7.2.jar:lib/truezip-swing-7.7.2.jar:lib/weblaf-1.29.jar:lib/xmlpull-1.1.3.4d_b4_min.jar:lib/xz-1.0.jar org.rr.jeborker.Jeboorker`.
