### ISSUE TITLE
Suddenly message: the system cannot find the specified file

### ISSUE THREAD

**Issue by har2121** [meerkatzenwildschein/jeboorker#27]
When I click on jeboorker.vbs I have the following errormessage:

Script: c:\Program Files (x86)\Jeboorker\Jeboorker.vbs
Line: 8
Teken: 1
Error: The system cannot find the specified file
Code: 80070002
Source: (null)

I've installed Jeboorker 1.29 again, but when I start jeboorker.vbs I keep this message.

What's going wrong?

NB: I remember now that I made a system scan with Bitdefender. After that I had this error. I looked in the log of the scan, but there were no files treated by Bitdefender connected to Jeboorker. However, is it possible that there is maybe a connection?

The jeboorker.vbs file contains the following lines:

Option Explicit

Dim strArguments, wshShell

strArguments = "javaw -splash:splashscreen.gif -client -Xmx4096m -XX:MaxHeapFreeRatio=20 -XX:MinHeapFreeRatio=10 -Djava.library.path=.\lib\ -cp .\lib\* org.rr.jeborker.Jeboorker"

Set wshShell = CreateObject( "WScript.Shell" )
wshShell.Run Trim( strArguments ), 0, False
Set wshShell = Nothing

I have, in consultation with the programmer (see issue ' Error Caused by: java.lang.OutOfMemoryError: Map failed at sun.nio.ch.FileChannelImpl.map0(Native Method) #13', changed the -Xmx512m to -Xmx4096m

**Comment by meerkatzenwildschein** [comment]
Unfortunately, I have no idea what the reason could be. If you simply reinstall Jeboorker, all files should be available again. The configuration and data are in the home directory and are not lost. Alternatively, I could imagine that perhaps the start screen has been lost? In this case just try to remove the parameter 'splash:splashscreen.gif'. Maybe this will help.

**Comment by har2121** [comment]
Thank you for your message.

I've reinstalled Jeboorker 1.2.9 but I have still the errormessage.

Then I've installed the newest Java version again. Then I got another errormessage from Java. After that I've installed Jeboorker 1.2.9 again. Now all works well.

Ys. Har
