### ISSUE TITLE
Windows installer - Default to English

### ISSUE THREAD

**Issue by electron0zero** [meerkatzenwildschein/jeboorker#4]
When I was installing software on my windows 10 machine.
It's installer was in a non English language(I couldn't read it, that's why i am calling it non English).
Maybe add a language selection or change the default installation language to English

---
Thanks,
Suraj

**Comment by meerkatzenwildschein** [comment]
Hi Suraj,
thanks for the hint. The language you've seen maybe is german. An exciting language but you're right, it is unmeant displaying the installer gui in german language. It's fixed with the next version. I hope you enjoy the software anyway.
Regards,
Meerkatzenwildschein
